try:
    print('1')
    x = 1 / 0
    print('2')
except:
    print('Oh dear, something went wrong!')
print('3')


# print('2') from the try block is missed